name: overwrite
version: 1.0.0
author: Christopher Best <bestchris@gmail.com>
description: Overwrite mode for text area elements in Dart
homepage: https://github.com/sirctseb/overwrite
environment:
  sdk: '>=2.0.0 <3.0.0'
documentation: http://sirctseb.github.io/overwrite
dependencies:
  logging: ^0.11.2
dev_dependencies:
  test: ^1.14.2
