name: overwrite
version: 0.1.0
author: Christopher Best <bestchris@gmail.com>
description: Overwrite mode for text area elements in Dart
homepage: https://github.com/sirctseb/overwrite
dev_dependencies:
  browser: any
  unittest: any
