name: overwrite
version: 0.2.7
author: Christopher Best <bestchris@gmail.com>
description: Overwrite mode for text area elements in Dart
homepage: https://github.com/sirctseb/overwrite
environment:
  sdk: '>=0.8.10+6 <2.0.0'
documentation: http://sirctseb.github.io/overwrite
dev_dependencies:
  browser: '>=0.9.0 <0.10.0'
  unittest: '>=0.9.0 <0.10.0'
