name: overwrite
version: 0.3.6-dev
author: Christopher Best <bestchris@gmail.com>
description: Overwrite mode for text area elements in Dart
homepage: https://github.com/sirctseb/overwrite
environment:
  sdk: '>=1.8.0 <2.0.0'
documentation: http://sirctseb.github.io/overwrite
dependencies:
  logging: ^0.11.2
  logging_handlers: ^0.8.0
dev_dependencies:
  browser: '>=0.9.0 <0.10.0'
  unittest: '>=0.9.0 <0.10.0'
